### ISSUE TITLE
Integration failed after last update

### ISSUE THREAD

**Issue by BartVanBouwel** [Elwinmage/ha-xsense-component#19]
Hi after last update (I believe the mqtt), the integration didn't work anymore.
I tried to downgrade but I couldn't get It to work again.

I get the following error: "Failed setup, will retry. module 'paho.mqtt.client' has no attribute 'CallbackAPlVersion'"

Any idea what could cause this?

Many thanks! I love this integration!!

**Comment by Elwinmage** [comment]
I revert commit to last version on my personal repositary.

1) Remove your ha-xsense-component

2) Change your custom repositary in HACS from https://github.com/Jarnsen/ha-xsense-component_test to https://github.com/Elwinmage/ha-xsense-component

3) Install ha-xsense-component

As soon as a stable version with mqtt support is available, I will apply commit it in the repositary.

**Comment by Jarnsen** [comment]
You Can delete it in hacs and install 1.0.8, 1.0.9 Beta is a Beta Release for Test, it will only work for Theo, that was unknown, But i will not delete the 1.0.9beta. Use the stable 1.0.8

**Comment by BartVanBouwel** [comment]
Perfect solution! It works again.
Thanks a lot.



Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Jarnsen ***@***.***>
Verzonden: Saturday, July 20, 2024 11:23:38 AM
Aan: Elwinmage/ha-xsense-component ***@***.***>
CC: Bart Van Bouwel ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Elwinmage/ha-xsense-component] Integration failed after last update (Issue #19)


You Can delete it in hacs and install 1.0.8, 1.0.9 Beta is a Beta Release for Test, it will only work for Theo, that was unknown, But i will not delete the 1.0.9beta. Use the stable 1.0.8
