### ISSUE TITLE
Failed Setup, XC04-WX CO alarm

### ISSUE THREAD

**Issue by draeg82** [Elwinmage/ha-xsense-component#20]
Hi,  I'm not sure where this issue is originating, when trying to set up the integration config, I add the account name and password, which authenticate, but then then I get the message below. The device is an XC04-WX CO alarm. 

Failed setup, will retry: XSense API Issue: Unable to retrieve station data: 404/{"message":"No shadow exists with name: 'XC04-WXEN450CB7~info_EN450CB7'","traceId":"d8d8e100-24e3-a003-c42d-c10ebf6a7748"}

**Comment by Jarnsen** [comment]
Use the newest Version, 1.0.10 is it at the moment.
