### ISSUE TITLE
Can't configure the username and password, no screen?

### ISSUE THREAD

**Issue by sjponnath-dst** [Elwinmage/ha-xsense-component#21]
I believe I installed it as indicated. However, I don't see it listed in integrations when I view integrations and looked for an unconfigured integration, only listed under the HACS integration as downloaded. 

Did I not install properly? 

Sorry it's a bit hard to understand the example install with it not being in English. 

Can you point me to an error I might have made in installation?   I did get through what should have been the install and then got the warning to restart Home Assistant.

**Comment by Elwinmage** [comment]
Hi,
have you hit the "add integration" button  on the bottom right of Parameters/Integrations and added xsense integration?
![image](https://github.com/user-attachments/assets/5786b279-5a1f-4401-a5b4-a66b295d4599)

**Comment by sjponnath-dst** [comment]
First, thank you for such a quick response! 
Ugh, this was the first time I installed something from HACS and I was attempting to integrate it from the HACS integration rather than go down to the Add Integration button.  
I used the button as you described and have the smoke detectors now reflected in HA. 
Thank you so much for the help. 
Steve

**Comment by sjponnath-dst** [comment]
I didn't see a way to reward you, How would that work? Can I send something for a cup of coffee maybe?

**Comment by Elwinmage** [comment]
Thank but I m only here for first level support and integration in HACS, @theosnel is the guy who develop this code (https://github.com/theosnel ). You can star is code.
