### ISSUE TITLE
SC07-WX - Standalone not working

### ISSUE THREAD

**Issue by johanneslasnik** [Elwinmage/ha-xsense-component#22]
Keine Geräte oder Entitäten
Einrichtung fehlgeschlagen, wird erneut versucht: XSense API Issue: Unable to retrieve station data: 404/{"message":"No shadow exists with name: 'SC07-WXEN4407FF~info_EN4407FF'","traceId":"c094f268-424a-d5cd-23cf-7c6048b9bb77"}

**Comment by MacPurschi** [comment]
Same Problem for me. Is the Basestation SBS50 required for integrating SC07-WX? I was hoping that this would not be necessary due to the wifi connection?!
