### ISSUE TITLE
Would this work with the x-sense mailbox thing?

### ISSUE THREAD

**Issue by akballow** [Elwinmage/ha-xsense-component#23]
I purchased this item and i am curious if you can support this item.

X-Sense Smart Mailbox Alarm, Wireless Long Range Mailbox Alert, Mailbox Sensor with SBS50 Base Station for Delivered Mail, SMA11
https://www.amazon.com/dp/B0CPLQ16K7?ref=ppx_yo2ov_dt_b_fed_asin_title&th=1

Or is there any pointers to how i can explore api calls on it to test?

**Comment by akballow** [comment]
I was able to login via the custom component and both the Base Station and Mailbox appear as devices, but they have no entities. 
![Screenshot 2024-09-24 at 2 24 36 PM](https://github.com/user-attachments/assets/f5d46960-58b4-43a1-a148-e6e89132ddbb)

**Comment by Elwinmage** [comment]
Hi, 
the work is made by @theosnel: 
This repo is only here to provide hacs installation and first level support.
For new features you can join this channel:
https://community.home-assistant.io/t/x-sense-security-is-it-possible-to-create-an-integration/534119
The last version can be found here:
https://github.com/theosnel/homeassistant-core/tree/xsense/homeassistant/components/xsense
