### ISSUE TITLE
Data are not refreshed automatically 

### ISSUE THREAD

**Issue by BrewToR** [Elwinmage/ha-xsense-component#24]
Hello, really nice job for this integration
Unfortunately, I cannot get the metrics auto refreshed.
Thanks in advance for your help

**Comment by Elwinmage** [comment]
Hi,
Are you using a second account or the same as your mobile device ?

**Comment by BrewToR** [comment]
Hello,
I tried both, and with an other account it looks really better but the refresh is still slow, like a metric every hour or less and sometimes no data returned

**Comment by Jarnsen** [comment]
This is a known bug, currently (without MQTT), will only be updated when you go into the xsense app. Theo a is currently working on a solution with MQTT and an API callback. If this is possible with the current HA version, there are also real-time updates.

**Comment by Jarnsen** [comment]
Should be work now.

**Comment by BrewToR** [comment]
I've just tried v1.0.10 and it works, metrics are updated well 
Thanks a lot for this nice integration !
