### ISSUE TITLE
Not working after Update

### ISSUE THREAD

**Issue by ItzChriZz** [Elwinmage/ha-xsense-component#25]
![IMG_5450](https://github.com/user-attachments/assets/e84b61b1-77b8-4776-9068-faab7264f2b0)

Hello, as in the Image described the Integration doesnt work anymore after Updating to Version 1.0.10

thanks.

**Comment by Bias84** [comment]
same here... :(

Logger: homeassistant.setup
Quelle: setup.py:269
Erstmals aufgetreten: 06:09:01 (1 Vorkommnisse)
Zuletzt protokolliert: 06:09:01

Setup failed for custom integration 'xsense': Requirements for xsense not found: ['paho-mqtt==2.1.0'].

**Comment by Jarnsen** [comment]
Is fixed
