### ISSUE TITLE
Entities empty

### ISSUE THREAD

**Issue by jrnas** [Elwinmage/ha-xsense-component#26]
Hello i installed the X-Sense HACs integration and all entities are empty.
I have a XS01-WX
<img width="974" alt="Bildschirmfoto 2024-10-09 um 15 33 11" src="https://github.com/user-attachments/assets/69ff4c5c-af70-4fce-9e03-e220f9d94894">

**Comment by Jarnsen** [comment]
You have to use the newest Version. 1.0.10 is it at the Moment.
