### ISSUE TITLE
Unexpected error fetching xsense data: 'state'

### ISSUE THREAD

**Issue by Robin19777** [Elwinmage/ha-xsense-component#6]
Hi, I have got some problems. I have installed this integration today, but it won't work...

![image](https://github.com/Elwinmage/ha-xsense-component/assets/166479764/abdc60e8-39e9-4cb0-8447-72432cbf147a)

`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.xsense
Quelle: helpers/update_coordinator.py:315
Integration: X-Sense Home Security
Erstmals aufgetreten: 12:34:33 (43 Vorkommnisse)
Zuletzt protokolliert: 13:20:59

Unexpected error fetching xsense data: 'state'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xsense/coordinator.py", line 49, in _async_update_data
    return await self.get_devices()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xsense/coordinator.py", line 87, in get_devices
    await self.xsense.get_station_state(s)
  File "/usr/local/lib/python3.12/site-packages/xsense/async_xsense.py", line 140, in get_station_state
    station.set_data(res['state']['reported'])
                     ~~~^^^^^^^^^
KeyError: 'state'
`

FYI:
- Acount information is correct 
- it is a second account with shared homes as needed

Do you have a solution or any suggestions for this, please?

**Comment by Elwinmage** [comment]
Hi, this repository is to permit to install the custom coponent with hacs.
Here is the main repositary maintain by the creator of this code:
https://github.com/theosnel/homeassistant-core/tree/xsense/homeassistant/components/xsense
You can move you issue there.
